# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AbastecaMe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AbastecaMe

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob', '~> 5.20.0'
  pod 'Firebase/Auth', '~> 5.20.0'
  pod 'Firebase/Core', '~> 5.20.0'
  # pod 'Firebase/Database', '~> 5.20.0'
  # pod 'Firebase/Functions', '~> 5.20.0'
  # pod 'Firebase/DynamicLinks', '~> 5.20.0'
  pod 'Firebase/Firestore', '~> 5.20.0'
  pod 'Firebase/Invites', '~> 5.20.0'
  # pod 'Firebase/Messaging', '~> 5.20.0'
  # pod 'Firebase/RemoteConfig', '~> 5.20.0'
  pod 'Firebase/Storage', '~> 5.20.0'
  pod 'Firebase/Performance', '~> 5.20.0'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
end
